Data Ingestion: Case Flags
hmcts/rd-commondata-dataload pull request #15
Opened 2021-12-10 16:29 UTC by ManishParyani

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-3605

### Change description ###
https://tools.hmcts.net/jira/browse/RDCC-3605

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-12-13 09:41 UTC, shreedhar-hmcts commented on config/checkstyle/checkstyle.xml
>      </module>
I think we dont refer this checkstyle.xml , rather use hmcts plugin which internally refers its own checkstyle

2021-12-13 09:44 UTC, shreedhar-hmcts commented on src/functionalTest/resources/application-functional.yml
> +    to:  manish.paryani@hmcts.net
please check if email service is really required in this case. I don't think so we have test cases has scenario to mail. Hmcts sec team is identifying the real email in the repo code and raising tickets. So please avoid if possible.

2021-12-13 14:40 UTC, ManishParyani commented on config/checkstyle/checkstyle.xml
>      </module>
Thanks For reviewing this PR, Issue has been Fixed, I have removed checkstyle config folder. 
And I have observed that in PRD repos we don't have checkstyle plugin and in LRD Project we are still using this type of config.

2021-12-13 14:40 UTC, ManishParyani commented on src/functionalTest/resources/application-functional.yml
> +    to:  manish.paryani@hmcts.net
Correct, We don't need this, I have removed the redundant code.

2021-12-14 10:11 UTC, SujeethKumarAri requested changes

2021-12-14 10:11 UTC, SujeethKumarAri commented on charts/rd-commondata-dataload/values.yaml
> +    postgresql:
Any idea why we need this config? I could see in jud data load this is under `job`

2021-12-14 10:11 UTC, SujeethKumarAri commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
> +class CommonDataApplicationExceptionAndAuditTest extends CommonDataIntegrationBaseTest {
I think the name should end with `FunctionalTest`

2021-12-14 10:11 UTC, SujeethKumarAri commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationTest.java
> +class CommonDataApplicationTest extends CommonDataIntegrationBaseTest {
I think the name should end with FunctionalTest

2021-12-14 10:11 UTC, SujeethKumarAri commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
> +class CommonDataFileStatusCheckTest extends CommonDataIntegrationBaseTest {
I think the name should end with FunctionalTest

2021-12-14 10:11 UTC, SujeethKumarAri commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
> +public class CommonDataFlagServiceLoadTest extends CommonDataIntegrationBaseTest {
I think the name should end with FunctionalTest

2021-12-14 10:11 UTC, SujeethKumarAri commented on src/main/resources/bootstrap.yaml
> +spring:
I think this file is not required

2021-12-14 10:11 UTC, SujeethKumarAri commented on src/main/resources/application.yaml
> -    import: "optional:configtree:/mnt/secrets/"
we need these changes but we need to include `rd` so that this config becomes `import: "optional:configtree:/mnt/secrets/rd"`

2021-12-14 10:17 UTC, shivajihmcts approved these changes

2021-12-14 11:07 UTC, ManishParyani commented on charts/rd-commondata-dataload/values.yaml
> +    postgresql:
Fixed

2021-12-14 11:07 UTC, ManishParyani commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
> +public class CommonDataFlagServiceLoadTest extends CommonDataIntegrationBaseTest {
Fixed

2021-12-14 11:07 UTC, ManishParyani commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagServiceLoadTest.java
> +public class CommonDataFlagServiceLoadTest extends CommonDataIntegrationBaseTest {
Fixed

2021-12-14 11:08 UTC, ManishParyani commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFileStatusCheckTest.java
> +class CommonDataFileStatusCheckTest extends CommonDataIntegrationBaseTest {
Fixed

2021-12-14 11:09 UTC, ManishParyani commented on src/main/resources/application.yaml
> -    import: "optional:configtree:/mnt/secrets/"
Same as above.

2021-12-14 11:10 UTC, ManishParyani commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationTest.java
> +class CommonDataApplicationTest extends CommonDataIntegrationBaseTest {
Fixed

2021-12-14 11:10 UTC, SujeethKumarAri approved these changes

2021-12-14 11:11 UTC, ManishParyani commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataApplicationExceptionAndAuditTest.java
> +class CommonDataApplicationExceptionAndAuditTest extends CommonDataIntegrationBaseTest {
Fixed

2021-12-14 13:46 UTC, merged