RDCC-5920: Common : Change the Flag Details upload into an ETL ingestion mechanism
hmcts/rd-commondata-dataload pull request #198
Opened 2022-12-05 09:21 UTC by ishratt

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-5920

### Change description ###
Added ETL ingestion mechanism for Flag Details file

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-12 10:11 UTC, kavithagade12 approved these changes

2022-12-12 22:10 UTC, rajkatla-hmcts requested changes

2022-12-12 22:10 UTC, rajkatla-hmcts commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagDetailsLoadTest.java
> +    void testFlagDetailsCsv_MissingHeader_Failure() throws Exception {
please cover all success/failure scenarios as per the acceptance criteria's and for failure scenarios assert error_description, field_in_error , key, row_id values in audit table.

2022-12-21 10:33 UTC, ishratt commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataFlagDetailsLoadTest.java
> +    void testFlagDetailsCsv_MissingHeader_Failure() throws Exception {
@rajkatla-hmcts thanks - this has now been addressed

2023-01-25 16:43 UTC, rajkatla-hmcts approved these changes

2023-01-26 11:21 UTC, merged