Create and Insert Additional Facilities table
hmcts/rd-commondata-dataload pull request #29
Opened 2021-12-15 18:57 UTC by sahitya-desireddy

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

2021-12-16 09:14 UTC, SujeethKumarAri requested changes

2021-12-16 09:14 UTC, SujeethKumarAri commented on src/main/resources/db/migration/V1_5__insert_additional_facilities.sql
> +	 ('InterpreterLanguage',NULL,'bel-bel','Belorussian',NULL,NULL,NULL,NULL,NULL,NULL,'Y');
This should be updated into `interpreter_and_sign_language table`

2021-12-16 10:15 UTC, sahitya-desireddy commented on src/main/resources/db/migration/V1_5__insert_additional_facilities.sql
> +	 ('InterpreterLanguage',NULL,'bel-bel','Belorussian',NULL,NULL,NULL,NULL,NULL,NULL,'Y');
Done Thank you

2021-12-16 17:26 UTC, SujeethKumarAri approved these changes

2021-12-17 10:14 UTC, shreedhar-hmcts approved these changes

2022-01-27 13:31 UTC, merged