DTSRD-1933
hmcts/rd-commondata-dataload pull request #304
Opened 2023-12-29 13:38 UTC by andy-m-b

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSRD-1933

### Change description ###

- Adding functionality to identify 0 byte characters and raise exception records for the rows where they are found, for further investigation.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-12-30 22:01 UTC, kiran-yenigala-hmcts commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +    public static final Set<String> ZERO_BYTE_CHARACTERS = Set.of("\u200B", " ");
if we can define this in application.yml file then it will be easy to add more zero byte characters dyamically

2023-12-30 22:02 UTC, kiran-yenigala-hmcts reviewed
Minor comment added

2024-01-17 08:53 UTC, kiran-yenigala-hmcts commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/DataQualityCheckConfiguration.java
> +@Configuration
why @Configuration is needed here?

@Component should be fine for this and then we can remove below code from  **src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/config/CommonDataCamelConfig.java**
    @Bean
    public DataQualityCheckConfiguration dataQualityCheckConfiguration() {
        return new DataQualityCheckConfiguration();
    }

2024-01-17 08:53 UTC, kiran-yenigala-hmcts commented on src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
> +    DataQualityCheckConfiguration dataQualityCheckConfiguration = new DataQualityCheckConfiguration();
DataQualityCheckConfiguration we can create mock instead of spy

2024-01-17 08:54 UTC, kiran-yenigala-hmcts requested changes
Couple of comments on this

2024-01-17 11:25 UTC, andy-m-b commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/DataQualityCheckConfiguration.java
> +@Configuration
Have changed the annotation, however the bean still needs to exist as the test fails with a bean dependency exception if it is not there.

2024-01-18 08:46 UTC, andy-m-b commented on src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
> +    DataQualityCheckConfiguration dataQualityCheckConfiguration = new DataQualityCheckConfiguration();
Resolved.

2024-01-24 11:06 UTC, SabinaHMCTS approved these changes

2024-01-24 11:29 UTC, kiran-yenigala-hmcts reviewed
Minor comment on this

2024-01-24 11:37 UTC, kiran-yenigala-hmcts commented on src/main/resources/application.yaml
> +  \u200B,
do we need comma at the end here?

2024-01-24 11:40 UTC, kiran-yenigala-hmcts approved these changes

2024-01-24 11:46 UTC, merged