Dtsrd 1992
hmcts/rd-commondata-dataload pull request #406
Opened 2024-10-09 13:36 UTC by SabinaHMCTS

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-10-21 11:32 UTC, lukasz-wolski requested changes
please see inlined comments

2024-10-21 11:32 UTC, lukasz-wolski commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataOtherCategoriesLoadTest.java
> +            containsString(pair.getValue1())
minor: value of zer0ByteCharacterErrorMsg can be used directly (or even inlined) here, no need to define a pair

2024-10-21 11:32 UTC, lukasz-wolski commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataOtherCategoriesLoadTest.java
> +        var audirResult = jdbcTemplate.queryForList(auditSchedulerQuery);
typo: please correct to auditResult

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
> +        List<FlagDetails> flagDetailsList;
it is clear from type that it is a list. adding 'List' as suffix increases verbosity, does not improve readability

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
> +        flagDetailsList = exchange.getIn().getBody() instanceof List
can be merged with declaration above

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
> +                                         List<FlagDetails> flagDetailsList) {
it is clear from type that it is a list. adding 'List' as suffix increases verbosity, does not improve readability

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessor.java
> +            .filter(flagDetail -> dataQualityCheckConfiguration.zeroByteCharacters.stream().anyMatch(
field dereference. please declare and call via accessor method (get...())

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
> +                    dataQualityCheckConfiguration.zeroByteCharacters.stream().anyMatch(
field dereference. please declare and call via accessor method (get...())

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/OtherCategoriesProcessor.java
> +            .filter(flagDetail -> dataQualityCheckConfiguration.zeroByteCharacters.stream().anyMatch(
field dereference. please declare and call via accessor method (get...())

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/OtherCategoriesProcessor.java
> +    private void processExceptionRecords(Exchange exchange,
Please consider a comment (at method level or inlined) addressing streams nested within streams. While it could cause a performance issue for streams containing a lot of data, in this instance both streams have very few elements (especially nested one) and should not be a concern.

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessor.java
> +    private void processExceptionRecords(Exchange exchange,
Please consider a comment (at method level or inlined) addressing streams nested within streams. While it could cause a performance issue for streams containing a lot of data, in this instance both streams have very few elements (especially nested one) and should not be a concern

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
> +    private void processExceptionRecords(Exchange exchange,
Please consider a comment (at method level or inlined) addressing streams nested within streams. While it could cause a performance issue for streams containing a lot of data, in this instance both streams have very few elements (especially nested one) and should not be a concern

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessor.java
> +                                         List<FlagService> flagServiceList) {
it is clear from type that it is a list. adding 'List' as suffix increases verbosity, does not improve readability

2024-10-21 11:32 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/OtherCategoriesProcessor.java
> +                                         List<OtherCategories> otherCategoriesList) {
it is clear from type that it is a list. adding 'List' as suffix increases verbosity, does not improve readability

2024-11-01 08:44 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
> +        List<FlagDetails> flagDetailsList;
done

2024-11-01 08:46 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessor.java
> +    private void processExceptionRecords(Exchange exchange,
nested streams were changed to forEach and common code moved to a single class

2024-11-01 08:46 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagDetailsProcessor.java
> +    private void processExceptionRecords(Exchange exchange,
nested streams were changed to forEach and common code moved to a single class

2024-11-01 08:46 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/FlagServiceProcessor.java
> +                                         List<FlagService> flagServiceList) {
done

2024-11-01 08:46 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/OtherCategoriesProcessor.java
> +                                         List<OtherCategories> otherCategoriesList) {
done

2024-11-01 09:12 UTC, mikebrownccd approved these changes
LGTM

2024-11-05 09:02 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/DataQualityCheckConfiguration.java
> +        if (((List) typeList.get(0)).get(0).getClass().getName().contains("OtherCategories")) {
what would happen if one of the expected values were not initialised? NPE is not handled anywhere. My impression is that this refactoring has made the code more complex

2024-11-05 09:03 UTC, lukasz-wolski approved these changes

2024-11-05 15:53 UTC, merged

2024-11-05 15:59 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/DataQualityCheckConfiguration.java
> +        if (((List) typeList.get(0)).get(0).getClass().getName().contains("OtherCategories")) {
added null check in procesor before all  if (categoriesList != null && !categoriesList.isEmpty()) {