DTSRD-72: Spring boot upgrade
hmcts/rd-commondata-dataload pull request #414
Opened 2024-10-30 15:15 UTC by kiran-yenigala-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-11-28 11:26 UTC, rapolaskaseliscgi approved these changes

2024-11-29 09:14 UTC, SabinaHMCTS approved these changes

2024-12-05 18:02 UTC, lukasz-wolski commented on build.gradle
> +  testImplementation group: 'org.testcontainers', name: 'postgresql', version: '1.20.2'
is there a reason for downgrading to version '1.20.2'?

2024-12-06 16:08 UTC, lukasz-wolski approved these changes
please see comment inlined

2024-12-06 16:19 UTC, kiran-yenigala-hmcts commented on build.gradle
> +  testImplementation group: 'org.testcontainers', name: 'postgresql', version: '1.20.2'
good spot, can change this back

2024-12-11 16:00 UTC, lukasz-wolski requested changes
please see comment inlined

2024-12-11 16:00 UTC, lukasz-wolski commented on build.gradle
> +  implementation ('com.github.hmcts:data-ingestion-lib:0.6.0.0-beta-14') {
please update to released version 0.6.0.0

2024-12-11 16:32 UTC, kiran-yenigala-hmcts commented on build.gradle
> +  implementation ('com.github.hmcts:data-ingestion-lib:0.6.0.0-beta-14') {
updated to 0.6.0.0

2025-01-16 15:14 UTC, SammiChong commented on .github/workflows/ci.yml
> +          java-version: 17
As discussed, we will add JDK 21 upgrade to this PR.

2025-01-20 13:42 UTC, rajkatla-hmcts approved these changes

2025-01-20 13:46 UTC, merged