DTSRD-3529. add 2 extra columns in the LOV table
hmcts/rd-commondata-dataload pull request #428
Opened 2024-11-11 11:45 UTC by SabinaHMCTS

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-11-20 10:02 UTC, mikebrownccd commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/testsupport/CommonDataFunctionalBaseTest.java
> +    protected void validateListOfValuesFile1(JdbcTemplate jdbcTemplate, String serviceSql,
Can this be given a more descriptive name?

2024-11-20 10:27 UTC, mikebrownccd commented on src/functionalTest/resources/sourceFiles/categories/list_of_values_duplicate_rec_case2.csv
> +CategoryKey,ServiceID,Key,Value_EN,Value_CY,Hinttext_EN,Hinttext_CY,Lov_Order,ParentCategory,ParentKey,Active,External_Reference,External_Reference_Type
The first line of the csv file (Headers) has 12 "," but lines 2 and 3 have 13 ","

2024-11-20 11:21 UTC, mikebrownccd commented on src/functionalTest/resources/sourceFiles/categories/list_of_values_failure_additional_header.csv
> +categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active,external_reference,external_reference_type,newHeader
2 commas added to the header but 3 added to the lines below

2024-11-20 12:02 UTC, lukasz-wolski requested changes
please see comments inlined

2024-11-20 12:02 UTC, lukasz-wolski commented on src/main/resources/db/migration/V1_8__alter_List_Of_Values.sql
> +ALTER TABLE list_of_values
minor: readability - please decide on either lower case or capitalised case across migration file

2024-11-20 12:25 UTC, mikebrownccd commented on src/main/resources/application-crd-list-of-values-router.yaml
> +    #csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active
commented code

2024-11-20 12:41 UTC, mikebrownccd commented on src/main/resources/db/migration/V1_1__init_tables.sql
> +INSERT INTO dbcommondata.flag_details (id,flag_code,value_en,value_cy,category_id) VALUES
i think that flyway might not like it if we modify and already applied delta

2024-11-20 16:27 UTC, mikebrownccd reviewed
I have left a few comments

2024-11-20 16:27 UTC, mikebrownccd commented on src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
> +    public static final String EXTERNAL_REFERENCE_ERROR_MSG = "Both external_reference_type and "
"external_reference_type" repeated in message string

2024-11-20 16:27 UTC, mikebrownccd commented on src/test/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessorTest.java
> +                .valueEN("Refusal of application under the EEA regulations ")
Was this previously part of the Zero Byte test?

2024-11-20 18:47 UTC, SabinaHMCTS commented on src/main/resources/application-crd-list-of-values-router.yaml
> +    #csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active
sorry . that's deleted now

2024-11-20 18:47 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +        + "external_reference_type value must be null or both must be not-null";
Changed .

will update jira

2024-11-20 18:47 UTC, SabinaHMCTS commented on bin/main/application-crd-list-of-values-router.yaml
> +    csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active,
done

2024-11-21 09:20 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +        + "external_reference_type value must be null or both must be not-null";
Original wording still present. Do not see an entry in jira ticket regarding error message. Please confirm whether this is intended

2024-11-21 09:28 UTC, lukasz-wolski approved these changes
please see comment inlined

2024-11-21 09:57 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +        + "external_reference_type value must be null or both must be not-null";
updated

2024-11-21 09:58 UTC, merged

2024-11-21 09:58 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +        + "external_reference_type value must be null or both must be not-null";
https://tools.hmcts.net/jira/browse/DTSRD-3529 does not contain any updates. Which Jira ticket are you referring to?

2024-11-21 10:04 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +        + "external_reference_type value must be null or both must be not-null";
https://tools.hmcts.net/jira/browse/DTSRD-3530