DTSRD-3529. According to the changed requirement.
hmcts/rd-commondata-dataload pull request #431
Opened 2024-11-25 18:33 UTC by SabinaHMCTS

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-11-26 09:03 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +                          String fieldError,Exchange exchange,String message) {
this is the change ..only this method changed .. fetchExistingRecords method was deleted

2024-11-26 09:04 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +        finalCategoriesList.removeAll(invalidCategories);
this is the actual change ... removing faulty records if any from final list and still loading file

2024-11-26 10:23 UTC, mikebrownccd commented on src/functionalTest/resources/sourceFiles/otherCategories/other_categories_0_byte_character.csv
> +categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active,external_reference,external_reference_type
2 commas added to header, 3 commas added to data rows. maybe on purpose

2024-11-26 10:25 UTC, mikebrownccd commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/CategoriesMapper.java
> +            categories.getExternalReference(),
maybe list can be reformatted

2024-11-26 10:26 UTC, mikebrownccd commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/CommonMapper.java
> +                                             String externalReferenceType, String lovOrder) {
params should align

2024-11-26 10:27 UTC, mikebrownccd commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/OtherCategoriesMapper.java
> +                                   categories.getExternalReferenceType(),categories.getLovOrder());
list can be reformatted

2024-11-26 10:52 UTC, mikebrownccd commented on src/main/resources/db/migration/V1_1__init_tables.sql
> + INSERT INTO dbcommondata.panel_member_type (categorykey,serviceid,"key",value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active) VALUES
i don't think flyway likes the already applied deltas to be modified

2024-11-26 11:08 UTC, SabinaHMCTS commented on src/functionalTest/resources/sourceFiles/otherCategories/other_categories_0_byte_character.csv
> +categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active,external_reference,external_reference_type
done

2024-11-26 11:09 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/CategoriesMapper.java
> +            categories.getExternalReference(),
its auto aligned by IDE

2024-11-26 11:09 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/OtherCategoriesMapper.java
> +                                   categories.getExternalReferenceType(),categories.getLovOrder());
its auto aligned by IDE

2024-11-26 11:35 UTC, SabinaHMCTS commented on src/main/resources/db/migration/V1_1__init_tables.sql
> + INSERT INTO dbcommondata.panel_member_type (categorykey,serviceid,"key",value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active) VALUES
removed change should not have been checked in

2024-11-26 12:00 UTC, mikebrownccd approved these changes
LGTM

2024-11-26 12:05 UTC, lukasz-wolski requested changes
Test are nicely formatted.
Implementation would benefit from same level of attention.

Please see comments inlined.

2024-11-26 12:15 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/DataQualityCheckConfiguration.java
>              JsrValidatorInitializer<FlagDetails> flagDetailsJsrValidatorInitializer =
removed

2024-11-26 12:15 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +                    && !category.getExternalReferenceType().isEmpty())
done

2024-11-26 12:15 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/mapper/CategoriesMapper.java
> +                                   categories.getExternalReferenceType(), categories.getLovOrder());
done

2024-11-26 12:22 UTC, lukasz-wolski requested changes
please see comment inlined

2024-11-26 12:24 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/DataQualityCheckConfiguration.java
>              JsrValidatorInitializer<FlagDetails> flagDetailsJsrValidatorInitializer =
'validator' method parameter no longer used by method implementation, please remove it

2024-11-26 13:31 UTC, rajkatla-hmcts requested changes

2024-11-26 13:31 UTC, rajkatla-hmcts commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
>              UPLOAD_LIST_OF_VALUES_FILE_NAME
Create test cases to cover below scenarios, please :

1. All records contain null external_reference_type and null external_reference
2. Missing new headers

2024-11-26 15:26 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/camel/processor/CategoriesProcessor.java
> +        + "external_reference_type value must be null or both must be not-null";
any suggestion

2024-11-26 15:26 UTC, SabinaHMCTS commented on src/main/java/uk/gov/hmcts/reform/rd/commondata/configuration/DataQualityCheckConfiguration.java
>                                              JsrValidatorInitializer<T> validator) {
removed

2024-11-26 15:42 UTC, rajkatla-hmcts commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
>              UPLOAD_LIST_OF_VALUES_FILE_NAME
@SabinaHMCTS as discussed , ignore the missing header scenario for now as you will need more time for that, i will create a separate ticket to cover that and for now just cover 1'st scenario

2024-11-27 09:14 UTC, SabinaHMCTS commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
>              UPLOAD_LIST_OF_VALUES_FILE_NAME
thank you. for 1.All records contain null external_reference_type and null external_reference .. do we need a test case success scenerio - upload without external reference? and show that the values are null?

2024-11-27 09:37 UTC, SabinaHMCTS commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
>              UPLOAD_LIST_OF_VALUES_FILE_NAME
added testListOfValuesAllRecordsContainNullExternalReferenceTypeAndNullExternalReferenceSuccess

2024-11-27 10:45 UTC, lukasz-wolski approved these changes
please see suggestion inlined

2024-11-27 11:10 UTC, SabinaHMCTS commented on src/functionalTest/java/uk/gov/hmcts/reform/rd/commondata/cameltest/CommonDataCategoriesLoadTest.java
> +        assertThat(listOfValues.get(0).get("external_reference_type")).isEqualTo("");
Postgress treats empty values as empty and not null unless its explicitly sent as null, unlike Oracle which will convert .
for lov , if the csv has sent empty values its saves as empty , but fro lov order before we save file there is a chack in code / mapper
if (isBlank(lovOrder)) {
            categoriesRow.put("lov_order", null);
        } else {
            categoriesRow.put("lov_order", Long.valueOf(trim(lovOrder)));
        }
so we explicitly add null in the db so thsts the only column. witjh null values

2024-11-28 12:49 UTC, rajkatla-hmcts approved these changes

2024-11-28 15:09 UTC, merged