Feat:Create new table and insert data for Flag Details
hmcts/rd-commondata-dataload pull request #6
Opened 2021-12-03 13:29 UTC by shivajihmcts

### JIRA link  ###

https://tools.hmcts.net/jira/browse/RDCC-3604

### Change description ###

Create new table and insert data for Flag Details

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2021-12-03 13:49 UTC, ishratt commented on src/main/resources/db/migration/V1_2__init_table_flag_details.sql
> +	 (1,'CF0001','Case','',0),
can we use `null` for the nullable fields instead of `''`?

2021-12-03 14:06 UTC, SujeethKumarAri requested changes

2021-12-03 14:06 UTC, SujeethKumarAri commented on src/main/resources/application.yaml
> +    enabled: ${FLYWAY_ENABLED:true}
Can we default this to `false` for safer side? and enable only in PR

2021-12-03 14:06 UTC, SujeethKumarAri commented on src/main/resources/db/migration/V1_2__init_table_flag_details.sql
> +DROP TABLE  IF EXISTS  flag_details;
No need to drop as the above V1 script will run only in PR. so everytime a PR is created it will create fresh table

2021-12-03 14:06 UTC, SujeethKumarAri commented on src/main/resources/db/migration/V1_2__init_table_flag_details.sql
> +create table flag_details(
No need to create it again

2021-12-03 14:16 UTC, SujeethKumarAri commented on src/main/resources/application.yaml
> +    enabled: ${FLYWAY_ENABLED:true}
or else set `FLYWAY_ENABLED: false` in `values.yaml` and set `FLYWAY_ENABLED: true` in `preview.yaml`

2021-12-04 16:59 UTC, ManishParyani requested changes
Lets Discuss before merging this PR.

2021-12-06 11:08 UTC, shivajihmcts commented on src/main/resources/db/migration/V1_2__init_table_flag_details.sql
> +	 (1,'CF0001','Case','',0),
Values are common from the csv so its should be as it is.

2021-12-06 11:08 UTC, shivajihmcts commented on src/main/resources/application.yaml
> +    enabled: ${FLYWAY_ENABLED:true}
done

2021-12-06 11:08 UTC, shivajihmcts commented on src/main/resources/db/migration/V1_2__init_table_flag_details.sql
> +create table flag_details(
done

2021-12-06 11:22 UTC, SujeethKumarAri approved these changes

2021-12-06 12:22 UTC, ManishParyani approved these changes

2021-12-06 12:26 UTC, merged