Feat:Java 17 Migration for Common Reference Data
hmcts/rd-commondata-dataload pull request #88
Opened 2022-04-04 17:33 UTC by shivajihmcts

### JIRA link  ###
https://tools.hmcts.net/jira/browse/RDCC-4352

### Change description ###
Java 17 Migration for Common Reference Data

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-04-08 11:39 UTC, AdilOoze approved these changes
Please run PR against Nightly to confirm Mutation Tests are passing on Jenkins

2022-04-08 12:47 UTC, shreedhar-hmcts approved these changes

2022-04-08 12:54 UTC, AdilOoze requested changes
Your PR is failing in Nightly Build at the Mutation step, please include the changes in this PR to fix this issue: https://github.com/hmcts/rd-user-profile-api/pull/809

2022-04-08 15:00 UTC, AdilOoze approved these changes

2022-04-26 11:00 UTC, kavithagade12 approved these changes

2022-04-27 07:39 UTC, merged